const siteData = [
	{
		"name": "Waterston",
		"location": "6016 Dibbert Lakes",
		"description": "Eaque veritatis nisi error illum.",
		"price": "11",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: false",
			"petAllowed: true",
			"toilets: true",
			"campfire: true",
			"water: false",
			"showers: true",
			"trash: true",
			"hotTub: true",
			"picnicTable: true",
			"wifi: false",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: false",
			"wildlifeWatching: true",
			"biking: true",
			"boating: false",
			"offRoading: true",
			"climbing: true",
			"snowSports: false",
			"horsebackRiding: false",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "East Samantamouth",
		"location": "4753 Wilderman Meadow",
		"description": "Et eveniet et ea dolorum.",
		"price": "37",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: false",
			"petAllowed: false",
			"toilets: true",
			"campfire: true",
			"water: true",
			"showers: false",
			"trash: true",
			"hotTub: true",
			"picnicTable: false",
			"wifi: true",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: true",
			"biking: true",
			"boating: false",
			"offRoading: true",
			"climbing: true",
			"snowSports: true",
			"horsebackRiding: false",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "North Dovie",
		"location": "632 Rogers Drive",
		"description": "Iusto et veniam non quo.",
		"price": "3",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: false",
			"toilets: true",
			"campfire: false",
			"water: true",
			"showers: false",
			"trash: false",
			"hotTub: true",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: false",
			"biking: false",
			"boating: false",
			"offRoading: true",
			"climbing: true",
			"snowSports: true",
			"horsebackRiding: true",
			"surfing: false",
			"windSport: false"
		]
	},
	{
		"name": "Hackensack",
		"location": "1952 Audrey Lights",
		"description": "Dolores odit molestiae repudiandae dolor.",
		"price": "33",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: false",
			"petAllowed: true",
			"toilets: false",
			"campfire: true",
			"water: false",
			"showers: false",
			"trash: true",
			"hotTub: false",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: false",
			"paddling: false",
			"birdWatching: true",
			"wildlifeWatching: true",
			"biking: true",
			"boating: true",
			"offRoading: false",
			"climbing: true",
			"snowSports: false",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "West Bryceview",
		"location": "0048 Cummings Course",
		"description": "Voluptatem unde mollitia quo recusandae.",
		"price": "23",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: false",
			"petAllowed: false",
			"toilets: true",
			"campfire: false",
			"water: false",
			"showers: true",
			"trash: true",
			"hotTub: true",
			"picnicTable: true",
			"wifi: false",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: false",
			"biking: false",
			"boating: true",
			"offRoading: false",
			"climbing: true",
			"snowSports: false",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: false"
		]
	},
	{
		"name": "Ilafort",
		"location": "8266 Kreiger Locks",
		"description": "Accusantium fuga ut quam est.",
		"price": "38",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: false",
			"campfire: true",
			"water: false",
			"showers: false",
			"trash: false",
			"hotTub: true",
			"picnicTable: true",
			"wifi: false",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: false",
			"paddling: true",
			"birdWatching: false",
			"wildlifeWatching: true",
			"biking: false",
			"boating: false",
			"offRoading: true",
			"climbing: false",
			"snowSports: true",
			"horsebackRiding: true",
			"surfing: false",
			"windSport: false"
		]
	},
	{
		"name": "Fort Amy",
		"location": "68971 Ally Harbors",
		"description": "Vel assumenda et iure ullam.",
		"price": "41",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: false",
			"petAllowed: true",
			"toilets: true",
			"campfire: false",
			"water: true",
			"showers: false",
			"trash: true",
			"hotTub: true",
			"picnicTable: false",
			"wifi: true",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: false",
			"biking: true",
			"boating: true",
			"offRoading: false",
			"climbing: true",
			"snowSports: false",
			"horsebackRiding: true",
			"surfing: false",
			"windSport: true"
		]
	},
	{
		"name": "North Mariaborough",
		"location": "5510 Wava Forges",
		"description": "Voluptatem eum eaque fugit id.",
		"price": "7",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: true",
			"campfire: true",
			"water: false",
			"showers: false",
			"trash: false",
			"hotTub: true",
			"picnicTable: false",
			"wifi: true",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: false",
			"birdWatching: true",
			"wildlifeWatching: false",
			"biking: true",
			"boating: true",
			"offRoading: false",
			"climbing: true",
			"snowSports: false",
			"horsebackRiding: false",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "Caitlynfield",
		"location": "91582 Payton Meadow",
		"description": "Et quo repellendus commodi officiis.",
		"price": "20",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: false",
			"campfire: true",
			"water: false",
			"showers: true",
			"trash: true",
			"hotTub: true",
			"picnicTable: true",
			"wifi: false",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: true",
			"biking: false",
			"boating: false",
			"offRoading: false",
			"climbing: false",
			"snowSports: false",
			"horsebackRiding: true",
			"surfing: false",
			"windSport: false"
		]
	},
	{
		"name": "Barnstable Town",
		"location": "53769 Stanton Cliff",
		"description": "Placeat molestiae necessitatibus hic laudantium.",
		"price": "3",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: true",
			"campfire: true",
			"water: false",
			"showers: true",
			"trash: true",
			"hotTub: false",
			"picnicTable: false",
			"wifi: false",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: true",
			"biking: true",
			"boating: false",
			"offRoading: true",
			"climbing: false",
			"snowSports: true",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "Namebury",
		"location": "5880 Letha Circle",
		"description": "Consequatur rerum voluptatem nostrum exercitationem.",
		"price": "17",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: false",
			"petAllowed: true",
			"toilets: true",
			"campfire: true",
			"water: true",
			"showers: false",
			"trash: false",
			"hotTub: true",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: true",
			"paddling: false",
			"birdWatching: true",
			"wildlifeWatching: true",
			"biking: true",
			"boating: true",
			"offRoading: true",
			"climbing: true",
			"snowSports: true",
			"horsebackRiding: true",
			"surfing: false",
			"windSport: false"
		]
	},
	{
		"name": "O'Connerburgh",
		"location": "9748 Lynch Ramp",
		"description": "Quas culpa itaque omnis fuga.",
		"price": "31",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: true",
			"campfire: true",
			"water: true",
			"showers: false",
			"trash: true",
			"hotTub: true",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: false",
			"paddling: false",
			"birdWatching: true",
			"wildlifeWatching: false",
			"biking: true",
			"boating: true",
			"offRoading: true",
			"climbing: true",
			"snowSports: true",
			"horsebackRiding: true",
			"surfing: false",
			"windSport: false"
		]
	},
	{
		"name": "Lewisville",
		"location": "602 Melyna Circles",
		"description": "Magni quo corrupti rerum fuga.",
		"price": "6",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: false",
			"petAllowed: true",
			"toilets: true",
			"campfire: true",
			"water: true",
			"showers: true",
			"trash: false",
			"hotTub: false",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: false",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: false",
			"biking: false",
			"boating: false",
			"offRoading: true",
			"climbing: false",
			"snowSports: true",
			"horsebackRiding: true",
			"surfing: false",
			"windSport: true"
		]
	},
	{
		"name": "East Salvatore",
		"location": "343 Terry Springs",
		"description": "Nihil assumenda hic porro fuga.",
		"price": "29",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: false",
			"petAllowed: true",
			"toilets: true",
			"campfire: true",
			"water: true",
			"showers: false",
			"trash: true",
			"hotTub: false",
			"picnicTable: true",
			"wifi: false",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: false",
			"paddling: true",
			"birdWatching: false",
			"wildlifeWatching: true",
			"biking: false",
			"boating: true",
			"offRoading: false",
			"climbing: false",
			"snowSports: true",
			"horsebackRiding: true",
			"surfing: false",
			"windSport: false"
		]
	},
	{
		"name": "Raynorville",
		"location": "0946 Madalyn Place",
		"description": "Ut dicta esse molestiae dolore.",
		"price": "29",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: false",
			"toilets: false",
			"campfire: false",
			"water: false",
			"showers: true",
			"trash: false",
			"hotTub: false",
			"picnicTable: true",
			"wifi: false",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: true",
			"biking: false",
			"boating: false",
			"offRoading: false",
			"climbing: false",
			"snowSports: true",
			"horsebackRiding: true",
			"surfing: false",
			"windSport: false"
		]
	},
	{
		"name": "Kristianmouth",
		"location": "48161 Okuneva Centers",
		"description": "Minus quam aut omnis cumque.",
		"price": "22",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: false",
			"campfire: true",
			"water: true",
			"showers: true",
			"trash: false",
			"hotTub: false",
			"picnicTable: true",
			"wifi: false",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: false",
			"paddling: false",
			"birdWatching: true",
			"wildlifeWatching: true",
			"biking: true",
			"boating: true",
			"offRoading: false",
			"climbing: false",
			"snowSports: false",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: false"
		]
	},
	{
		"name": "Port Joesph",
		"location": "7736 Bonita Trafficway",
		"description": "Omnis quaerat consequatur libero sunt.",
		"price": "34",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: true",
			"campfire: true",
			"water: false",
			"showers: false",
			"trash: true",
			"hotTub: true",
			"picnicTable: false",
			"wifi: true",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: true",
			"biking: false",
			"boating: false",
			"offRoading: true",
			"climbing: true",
			"snowSports: false",
			"horsebackRiding: false",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "East Minerva",
		"location": "71619 Kailey Stravenue",
		"description": "Quos sed qui est maxime.",
		"price": "4",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: false",
			"toilets: true",
			"campfire: true",
			"water: false",
			"showers: true",
			"trash: true",
			"hotTub: false",
			"picnicTable: false",
			"wifi: false",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: true",
			"biking: true",
			"boating: true",
			"offRoading: true",
			"climbing: false",
			"snowSports: false",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "Port Carson",
		"location": "28610 Nienow Branch",
		"description": "Accusantium maxime eligendi aut quis.",
		"price": "9",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: true",
			"campfire: true",
			"water: false",
			"showers: true",
			"trash: false",
			"hotTub: false",
			"picnicTable: true",
			"wifi: false",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: false",
			"paddling: false",
			"birdWatching: false",
			"wildlifeWatching: true",
			"biking: true",
			"boating: true",
			"offRoading: false",
			"climbing: false",
			"snowSports: true",
			"horsebackRiding: false",
			"surfing: false",
			"windSport: false"
		]
	},
	{
		"name": "Amarimouth",
		"location": "8504 Runte Divide",
		"description": "Esse minima animi ab magni.",
		"price": "37",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: false",
			"petAllowed: true",
			"toilets: true",
			"campfire: false",
			"water: true",
			"showers: false",
			"trash: true",
			"hotTub: true",
			"picnicTable: true",
			"wifi: false",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: true",
			"paddling: false",
			"birdWatching: true",
			"wildlifeWatching: true",
			"biking: false",
			"boating: false",
			"offRoading: true",
			"climbing: true",
			"snowSports: false",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "East Cordie",
		"location": "315 Colten Plains",
		"description": "Optio non aperiam quos vitae.",
		"price": "6",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: false",
			"petAllowed: true",
			"toilets: false",
			"campfire: false",
			"water: true",
			"showers: true",
			"trash: true",
			"hotTub: true",
			"picnicTable: false",
			"wifi: false",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: true",
			"biking: true",
			"boating: true",
			"offRoading: false",
			"climbing: false",
			"snowSports: true",
			"horsebackRiding: true",
			"surfing: false",
			"windSport: true"
		]
	},
	{
		"name": "Ankundingstead",
		"location": "64398 Markus Way",
		"description": "Dolorum modi voluptatem ea officiis.",
		"price": "39",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: false",
			"petAllowed: true",
			"toilets: true",
			"campfire: true",
			"water: true",
			"showers: true",
			"trash: false",
			"hotTub: true",
			"picnicTable: true",
			"wifi: false",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: false",
			"paddling: false",
			"birdWatching: false",
			"wildlifeWatching: false",
			"biking: false",
			"boating: true",
			"offRoading: true",
			"climbing: true",
			"snowSports: true",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "New Orleans",
		"location": "6685 Hettinger Plain",
		"description": "Placeat amet consequatur doloribus illo.",
		"price": "8",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: false",
			"petAllowed: false",
			"toilets: true",
			"campfire: false",
			"water: false",
			"showers: true",
			"trash: false",
			"hotTub: true",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: false",
			"paddling: false",
			"birdWatching: false",
			"wildlifeWatching: true",
			"biking: true",
			"boating: false",
			"offRoading: true",
			"climbing: true",
			"snowSports: false",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "Nienowland",
		"location": "6872 Alexandro Fords",
		"description": "Ut voluptas ad et ipsum.",
		"price": "37",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: false",
			"petAllowed: true",
			"toilets: true",
			"campfire: true",
			"water: true",
			"showers: false",
			"trash: true",
			"hotTub: true",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: false",
			"wildlifeWatching: true",
			"biking: true",
			"boating: true",
			"offRoading: false",
			"climbing: true",
			"snowSports: false",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: false"
		]
	},
	{
		"name": "East Carleybury",
		"location": "67526 Champlin Knoll",
		"description": "Nemo quis amet facilis eum.",
		"price": "22",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: false",
			"petAllowed: true",
			"toilets: false",
			"campfire: false",
			"water: true",
			"showers: true",
			"trash: true",
			"hotTub: false",
			"picnicTable: true",
			"wifi: false",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: false",
			"paddling: true",
			"birdWatching: false",
			"wildlifeWatching: true",
			"biking: false",
			"boating: false",
			"offRoading: true",
			"climbing: false",
			"snowSports: false",
			"horsebackRiding: false",
			"surfing: false",
			"windSport: true"
		]
	},
	{
		"name": "Fort Joshuah",
		"location": "57684 Allen Grove",
		"description": "Velit maiores quo eaque perferendis.",
		"price": "33",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: false",
			"petAllowed: true",
			"toilets: false",
			"campfire: true",
			"water: false",
			"showers: true",
			"trash: false",
			"hotTub: false",
			"picnicTable: true",
			"wifi: false",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: false",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: false",
			"biking: false",
			"boating: true",
			"offRoading: true",
			"climbing: false",
			"snowSports: true",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "Jabariboro",
		"location": "70637 Keebler Island",
		"description": "In sed nobis vel quis.",
		"price": "27",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: false",
			"toilets: false",
			"campfire: false",
			"water: true",
			"showers: false",
			"trash: false",
			"hotTub: false",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: false",
			"paddling: true",
			"birdWatching: false",
			"wildlifeWatching: true",
			"biking: true",
			"boating: true",
			"offRoading: false",
			"climbing: true",
			"snowSports: false",
			"horsebackRiding: true",
			"surfing: false",
			"windSport: false"
		]
	},
	{
		"name": "Koelpinstad",
		"location": "251 Schamberger Viaduct",
		"description": "Numquam dolor corrupti architecto dolorem.",
		"price": "19",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: false",
			"petAllowed: false",
			"toilets: true",
			"campfire: false",
			"water: true",
			"showers: true",
			"trash: true",
			"hotTub: true",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: false",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: false",
			"biking: true",
			"boating: true",
			"offRoading: true",
			"climbing: false",
			"snowSports: false",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "Mayaguez",
		"location": "9093 Kemmer Station",
		"description": "Inventore exercitationem non soluta atque.",
		"price": "47",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: false",
			"petAllowed: false",
			"toilets: true",
			"campfire: false",
			"water: true",
			"showers: true",
			"trash: true",
			"hotTub: true",
			"picnicTable: true",
			"wifi: false",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: false",
			"paddling: false",
			"birdWatching: true",
			"wildlifeWatching: false",
			"biking: true",
			"boating: false",
			"offRoading: false",
			"climbing: true",
			"snowSports: true",
			"horsebackRiding: false",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "Lake Reynold",
		"location": "08064 Penelope Square",
		"description": "Natus voluptas quod dolorem autem.",
		"price": "20",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: false",
			"petAllowed: true",
			"toilets: true",
			"campfire: true",
			"water: true",
			"showers: true",
			"trash: false",
			"hotTub: false",
			"picnicTable: false",
			"wifi: true",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: false",
			"wildlifeWatching: true",
			"biking: true",
			"boating: false",
			"offRoading: false",
			"climbing: true",
			"snowSports: false",
			"horsebackRiding: false",
			"surfing: true",
			"windSport: false"
		]
	},
	{
		"name": "Bartolettiland",
		"location": "10916 Celine Pike",
		"description": "Aspernatur sit hic quas voluptatem.",
		"price": "12",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: false",
			"toilets: true",
			"campfire: true",
			"water: true",
			"showers: true",
			"trash: true",
			"hotTub: true",
			"picnicTable: true",
			"wifi: false",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: false",
			"birdWatching: true",
			"wildlifeWatching: true",
			"biking: true",
			"boating: false",
			"offRoading: true",
			"climbing: false",
			"snowSports: true",
			"horsebackRiding: true",
			"surfing: false",
			"windSport: true"
		]
	},
	{
		"name": "Trompstad",
		"location": "0061 Kamren Tunnel",
		"description": "Blanditiis atque incidunt enim ea.",
		"price": "38",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: false",
			"petAllowed: true",
			"toilets: true",
			"campfire: false",
			"water: true",
			"showers: true",
			"trash: false",
			"hotTub: true",
			"picnicTable: false",
			"wifi: false",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: false",
			"paddling: true",
			"birdWatching: false",
			"wildlifeWatching: false",
			"biking: false",
			"boating: false",
			"offRoading: true",
			"climbing: false",
			"snowSports: true",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "Ileneview",
		"location": "46756 Legros Motorway",
		"description": "Repellendus qui culpa tempora molestiae.",
		"price": "18",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: false",
			"toilets: true",
			"campfire: false",
			"water: false",
			"showers: false",
			"trash: false",
			"hotTub: true",
			"picnicTable: true",
			"wifi: false",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: false",
			"paddling: true",
			"birdWatching: false",
			"wildlifeWatching: true",
			"biking: false",
			"boating: true",
			"offRoading: false",
			"climbing: true",
			"snowSports: false",
			"horsebackRiding: true",
			"surfing: false",
			"windSport: true"
		]
	},
	{
		"name": "New Emilio",
		"location": "5105 Shields Islands",
		"description": "Sequi sed quo nemo minus.",
		"price": "48",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: false",
			"toilets: false",
			"campfire: true",
			"water: true",
			"showers: false",
			"trash: true",
			"hotTub: true",
			"picnicTable: false",
			"wifi: true",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: false",
			"wildlifeWatching: true",
			"biking: true",
			"boating: false",
			"offRoading: false",
			"climbing: true",
			"snowSports: false",
			"horsebackRiding: false",
			"surfing: false",
			"windSport: true"
		]
	},
	{
		"name": "South Eltonton",
		"location": "2223 Ullrich Hills",
		"description": "Fugiat quas aut error necessitatibus.",
		"price": "19",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: false",
			"petAllowed: true",
			"toilets: true",
			"campfire: true",
			"water: false",
			"showers: true",
			"trash: true",
			"hotTub: true",
			"picnicTable: false",
			"wifi: true",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: true",
			"paddling: false",
			"birdWatching: true",
			"wildlifeWatching: false",
			"biking: true",
			"boating: true",
			"offRoading: false",
			"climbing: false",
			"snowSports: true",
			"horsebackRiding: true",
			"surfing: false",
			"windSport: true"
		]
	},
	{
		"name": "Fairfield",
		"location": "6773 Wolf Squares",
		"description": "Accusamus numquam quas totam facilis.",
		"price": "20",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: true",
			"petAllowed: false",
			"toilets: true",
			"campfire: true",
			"water: false",
			"showers: true",
			"trash: true",
			"hotTub: false",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: false",
			"biking: true",
			"boating: false",
			"offRoading: true",
			"climbing: true",
			"snowSports: false",
			"horsebackRiding: true",
			"surfing: false",
			"windSport: false"
		]
	},
	{
		"name": "Stamford",
		"location": "931 Lubowitz Loaf",
		"description": "Vero et ex vel repellendus.",
		"price": "15",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: false",
			"campfire: false",
			"water: false",
			"showers: false",
			"trash: false",
			"hotTub: true",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: false",
			"biking: true",
			"boating: true",
			"offRoading: false",
			"climbing: false",
			"snowSports: false",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "Lake Morton",
		"location": "390 Pasquale Estate",
		"description": "Quia aut quaerat praesentium velit.",
		"price": "46",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: true",
			"petAllowed: false",
			"toilets: true",
			"campfire: true",
			"water: true",
			"showers: true",
			"trash: true",
			"hotTub: true",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: true",
			"biking: true",
			"boating: true",
			"offRoading: false",
			"climbing: true",
			"snowSports: false",
			"horsebackRiding: false",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "Port Paigeside",
		"location": "62556 Dickens Causeway",
		"description": "Et dolores molestias eos sequi.",
		"price": "46",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: true",
			"petAllowed: false",
			"toilets: false",
			"campfire: true",
			"water: false",
			"showers: false",
			"trash: false",
			"hotTub: false",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: true",
			"biking: true",
			"boating: false",
			"offRoading: true",
			"climbing: false",
			"snowSports: true",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "East Orvillestead",
		"location": "38675 Powlowski Expressway",
		"description": "Numquam consequatur eos praesentium natus.",
		"price": "32",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: true",
			"campfire: false",
			"water: true",
			"showers: true",
			"trash: true",
			"hotTub: false",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: true",
			"biking: true",
			"boating: false",
			"offRoading: true",
			"climbing: true",
			"snowSports: true",
			"horsebackRiding: false",
			"surfing: false",
			"windSport: true"
		]
	},
	{
		"name": "Bothell",
		"location": "3797 Funk Burgs",
		"description": "Omnis omnis quis autem delectus.",
		"price": "28",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: true",
			"petAllowed: false",
			"toilets: true",
			"campfire: false",
			"water: true",
			"showers: false",
			"trash: true",
			"hotTub: true",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: false",
			"paddling: false",
			"birdWatching: true",
			"wildlifeWatching: true",
			"biking: true",
			"boating: true",
			"offRoading: true",
			"climbing: true",
			"snowSports: false",
			"horsebackRiding: false",
			"surfing: false",
			"windSport: false"
		]
	},
	{
		"name": "Altoona",
		"location": "8840 Heather Ford",
		"description": "Eum quibusdam quas delectus repellendus.",
		"price": "30",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: false",
			"petAllowed: false",
			"toilets: true",
			"campfire: false",
			"water: false",
			"showers: false",
			"trash: true",
			"hotTub: false",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: false",
			"birdWatching: false",
			"wildlifeWatching: false",
			"biking: false",
			"boating: true",
			"offRoading: false",
			"climbing: false",
			"snowSports: false",
			"horsebackRiding: false",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "Pasadena",
		"location": "696 Robin Turnpike",
		"description": "Voluptate excepturi dolorum placeat sunt.",
		"price": "45",
		"amenities": [
			"parking: false",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: true",
			"campfire: false",
			"water: true",
			"showers: true",
			"trash: false",
			"hotTub: false",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: false",
			"paddling: false",
			"birdWatching: true",
			"wildlifeWatching: false",
			"biking: false",
			"boating: true",
			"offRoading: false",
			"climbing: true",
			"snowSports: false",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: false"
		]
	},
	{
		"name": "Florissant",
		"location": "29852 Wilderman Roads",
		"description": "Ut qui est voluptatum eos.",
		"price": "30",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: false",
			"toilets: true",
			"campfire: true",
			"water: false",
			"showers: false",
			"trash: false",
			"hotTub: false",
			"picnicTable: false",
			"wifi: false",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: false",
			"paddling: false",
			"birdWatching: false",
			"wildlifeWatching: false",
			"biking: true",
			"boating: false",
			"offRoading: false",
			"climbing: true",
			"snowSports: true",
			"horsebackRiding: true",
			"surfing: false",
			"windSport: true"
		]
	},
	{
		"name": "Aniyaport",
		"location": "8266 Koss Parks",
		"description": "Qui molestias nemo et odit.",
		"price": "30",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: false",
			"campfire: true",
			"water: true",
			"showers: false",
			"trash: true",
			"hotTub: false",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: true",
			"paddling: false",
			"birdWatching: false",
			"wildlifeWatching: true",
			"biking: true",
			"boating: true",
			"offRoading: false",
			"climbing: true",
			"snowSports: false",
			"horsebackRiding: true",
			"surfing: true",
			"windSport: true"
		]
	},
	{
		"name": "Stephenside",
		"location": "2204 Ashly Lights",
		"description": "Autem eum alias quas enim.",
		"price": "20",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: false",
			"petAllowed: true",
			"toilets: true",
			"campfire: false",
			"water: true",
			"showers: true",
			"trash: false",
			"hotTub: false",
			"picnicTable: true",
			"wifi: false",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: false",
			"paddling: false",
			"birdWatching: true",
			"wildlifeWatching: true",
			"biking: true",
			"boating: true",
			"offRoading: false",
			"climbing: false",
			"snowSports: true",
			"horsebackRiding: false",
			"surfing: false",
			"windSport: false"
		]
	},
	{
		"name": "Linniefurt",
		"location": "736 Dietrich Extension",
		"description": "Non aut autem molestias officia.",
		"price": "38",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: false",
			"toilets: true",
			"campfire: false",
			"water: true",
			"showers: false",
			"trash: true",
			"hotTub: true",
			"picnicTable: true",
			"wifi: false",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: true",
			"paddling: true",
			"birdWatching: true",
			"wildlifeWatching: false",
			"biking: false",
			"boating: false",
			"offRoading: false",
			"climbing: true",
			"snowSports: true",
			"horsebackRiding: false",
			"surfing: false",
			"windSport: false"
		]
	},
	{
		"name": "Fort Jordi",
		"location": "247 Lizeth Falls",
		"description": "Ipsam placeat ut aspernatur corporis.",
		"price": "40",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: false",
			"petAllowed: false",
			"toilets: true",
			"campfire: true",
			"water: true",
			"showers: true",
			"trash: true",
			"hotTub: true",
			"picnicTable: true",
			"wifi: true",
			"cookingEquipment: false"
		],
		"activities": [
			"fishing: false",
			"paddling: false",
			"birdWatching: true",
			"wildlifeWatching: false",
			"biking: true",
			"boating: false",
			"offRoading: true",
			"climbing: false",
			"snowSports: false",
			"horsebackRiding: true",
			"surfing: false",
			"windSport: false"
		]
	},
	{
		"name": "Lake Tommie",
		"location": "20258 Judd Highway",
		"description": "Iure omnis reiciendis reprehenderit alias.",
		"price": "9",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: false",
			"petAllowed: true",
			"toilets: true",
			"campfire: true",
			"water: true",
			"showers: false",
			"trash: false",
			"hotTub: true",
			"picnicTable: false",
			"wifi: true",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: true",
			"paddling: false",
			"birdWatching: false",
			"wildlifeWatching: true",
			"biking: false",
			"boating: true",
			"offRoading: true",
			"climbing: false",
			"snowSports: true",
			"horsebackRiding: true",
			"surfing: false",
			"windSport: true"
		]
	},
	{
		"name": "Lemkefort",
		"location": "947 Sydnie Shore",
		"description": "Quia magni possimus sint dolores.",
		"price": "27",
		"amenities": [
			"parking: true",
			"wheelchairAccessible: true",
			"petAllowed: true",
			"toilets: false",
			"campfire: true",
			"water: true",
			"showers: true",
			"trash: false",
			"hotTub: true",
			"picnicTable: false",
			"wifi: true",
			"cookingEquipment: true"
		],
		"activities": [
			"fishing: false",
			"paddling: true",
			"birdWatching: false",
			"wildlifeWatching: true",
			"biking: true",
			"boating: true",
			"offRoading: true",
			"climbing: true",
			"snowSports: true",
			"horsebackRiding: true",
			"surfing: false",
			"windSport: false"
		]
	}
]

export default siteData;