const siteData = [
  {
    name: "Josephinetown",
    location: "Chapel Hill",
    description: "Corporis repudiandae eveniet enim similique.",
    rate: "19",
  },
  {
    name: "Port Lesleyview",
    location: "Chapel Hill",
    description: "Excepturi dolore natus in expedita.",
    rate: "16",
  },
  {
    name: "Lake D'angelo",
    location: "Raleigh",
    description: "Non perferendis nisi minima voluptate.",
    rate: "10",
  },
  {
    name: "Vitahaven",
    location: "Miami",
    description: "Ut nihil debitis recusandae debitis.",
    rate: "19",
  },
  {
    name: "New Tomasa",
    location: "Durham",
    description: "Voluptatem quas aliquid numquam deleniti.",
    rate: "12",
  },
  {
    name: "Hudsonberg",
    location: "Chapel Hill",
    description: "Aliquam tempore voluptas quia laboriosam.",
    rate: "28",
  },
  {
    name: "Kuvalisbury",
    location: "Lynchburg",
    description: "Nam ut distinctio quam dolor.",
    rate: "47",
  },
  {
    name: "Taylor",
    location: "Dallas",
    description: "Molestiae provident quam voluptatem deserunt.",
    rate: "49",
  },
  {
    name: "Floville",
    location: "Los Angeles",
    description: "Laborum aliquid dolores delectus explicabo.",
    rate: "38",
  },
  {
    name: "Brendonport",
    location: "Atlanta",
    description: "Perferendis aut distinctio nihil provident.",
    rate: "37",
  },
  {
    name: "Wymanfield",
    location: "Charlotte",
    description: "Quam asperiores aut nesciunt facilis.",
    rate: "38",
  },
  {
    name: "East Moriahside",
    location: "Austin",
    description: "Quisquam ad vel animi vel.",
    rate: "40",
  },
  {
    name: "North Vinceborough",
    location: "Arlington",
    description: "Minus quas vitae incidunt totam.",
    rate: "21",
  },
  {
    name: "West Maymie",
    location: "Arlington",
    description: "Dolore ut non incidunt eos.",
    rate: "43",
  },
  {
    name: "Hellerfurt",
    location: "47135 Maddison River",
    description: "Velit nihil et facere commodi.",
    rate: "41",
  },
  {
    name: "Dubuque",
    location: "Alexandria",
    description: "Necessitatibus possimus illum vel recusandae.",
    rate: "47",
  },
  {
    name: "Bethanyfield",
    location: "Alexandria",
    description: "Tempore autem sint aut animi.",
    rate: "35",
  },
  {
    name: "Port Braxtonfield",
    location: "Raleigh",
    description: "Nulla sunt nam deserunt tenetur.",
    rate: "17",
  },
  {
    name: "Bakersfield",
    location: "Chapel Hill",
    description: "Rem quae debitis quis quo.",
    rate: "31",
  },
  {
    name: "Breitenbergfort",
    location: "Durham",
    description: "Consequatur commodi porro voluptas quibusdam.",
    rate: "12",
  },
  {
    name: "Lake Aniya",
    location: "Charlotte",
    description: "Non velit quia et dolores.",
    rate: "29",
  },
  {
    name: "New Felipahaven",
    location: "Mount Airy",
    description: "Reprehenderit odit aut qui commodi.",
    rate: "36",
  },
  {
    name: "Dillanberg",
    location: "Greensboro",
    description: "Ut non ut eum iure.",
    rate: "19",
  },
  {
    name: "Olemouth",
    location: "Greensboro",
    description: "Nihil nihil suscipit id corrupti.",
    rate: "23",
  },
  {
    name: "Stammberg",
    location: "King",
    description: "Inventore voluptatem ex et nostrum.",
    rate: "42",
  },
  {
    name: "North Fredrick",
    location: "45276 Deonte Springs",
    description: "Modi quasi error nam cumque.",
    rate: "47",
  },
  {
    name: "Merced",
    location: "Tampa",
    description: "Est et at alias quidem.",
    rate: "12",
  },
  {
    name: "New Chasity",
    location: "Orlando",
    description: "Sed delectus ad corrupti ducimus.",
    rate: "27",
  },
  {
    name: "Farrellboro",
    location: "New York",
    description: "Quibusdam dignissimos natus aut soluta.",
    rate: "17",
  },
  {
    name: "Prohaskahaven",
    location: "Chapel Hill",
    description: "Animi qui inventore aut quasi.",
    rate: "37",
  },
  {
    name: "Pagacside",
    location: "Chapel Hill",
    description: "Voluptatibus rerum necessitatibus autem et.",
    rate: "34",
  },
  {
    name: "Leonorafurt",
    location: "Chapel Hill",
    description: "Non exercitationem aut voluptatibus ex.",
    rate: "25",
  },
  {
    name: "Dewittmouth",
    location: "Miami",
    description: "Incidunt optio sint aut ratione.",
    rate: "50",
  },
  {
    name: "El Dorado Hills",
    location: "miami",
    description: "Animi aut voluptas ut eum.",
    rate: "41",
  },
  {
    name: "Mattieborough",
    location: "Dallas",
    description: "Dicta consequuntur maxime culpa explicabo.",
    rate: "41",
  },
  {
    name: "Watsonville",
    location: "Austin",
    description: "Atque repudiandae officiis voluptates deleniti.",
    rate: "44",
  },
  {
    name: "Earlineshire",
    location: "Los Angeles",
    description: "Aut harum modi id qui.",
    rate: "19",
  },
  {
    name: "Cormierport",
    location: "San Diego",
    description: "Rerum quam ut quaerat nisi.",
    rate: "11",
  },
  {
    name: "Madisenfort",
    location: "Charlottesville",
    description: "Totam nulla repudiandae deserunt temporibus.",
    rate: "50",
  },
  {
    name: "Grand Island",
    location: "Charleston",
    description: "Libero laudantium corrupti optio voluptatum.",
    rate: "40",
  },
  {
    name: "Khalidside",
    location: "Charleston",
    description: "Placeat suscipit inventore odio deleniti.",
    rate: "33",
  },
  {
    name: "Fort Lilyancester",
    location: "Wilmington",
    description: "Qui molestiae at consectetur sed.",
    rate: "20",
  },
  {
    name: "West Lorna",
    location: "Wilmington",
    description: "Sint est nostrum velit optio.",
    rate: "17",
  },
  {
    name: "Kulasberg",
    location: "Fresno",
    description: "Dolore eveniet natus consequatur magnam.",
    rate: "44",
  },
  {
    name: "Peytonborough",
    location: "Boston",
    description: "Consequuntur dolores dolor inventore animi.",
    rate: "13",
  },
  {
    name: "Zoeystad",
    location: "Seattle",
    description: "Facere sint sit explicabo voluptate.",
    rate: "35",
  },
  {
    name: "Wymanburgh",
    location: "Portland",
    description: "Dolore optio sapiente nesciunt mollitia.",
    rate: "28",
  },
  {
    name: "New Kara",
    location: "Portland",
    description: "Doloremque ratione molestiae soluta labore.",
    rate: "14",
  },
  {
    name: "Welchland",
    location: "Seattle",
    description: "Molestias fugiat dolore quasi enim.",
    rate: "45",
  },
  {
    name: "Brentwood",
    location: "Miami",
    description: "Dolore facere tempore ut quia.",
    rate: "25",
  },
];

export default siteData
