const siteData = [
  {
    name: "Josephinetown",
    location: "356 Berge Shore",
    description: "Corporis repudiandae eveniet enim similique.",
    rate: "19",
  },
  {
    name: "Port Lesleyview",
    location: "88020 Jada Springs",
    description: "Excepturi dolore natus in expedita.",
    rate: "16",
  },
  {
    name: "Lake D'angelo",
    location: "64506 Kallie Stream",
    description: "Non perferendis nisi minima voluptate.",
    rate: "10",
  },
  {
    name: "Vitahaven",
    location: "5245 Schuppe Shore",
    description: "Ut nihil debitis recusandae debitis.",
    rate: "19",
  },
  {
    name: "New Tomasa",
    location: "1857 Braun Court",
    description: "Voluptatem quas aliquid numquam deleniti.",
    rate: "12",
  },
  {
    name: "Hudsonberg",
    location: "235 Pfeffer Circle",
    description: "Aliquam tempore voluptas quia laboriosam.",
    rate: "28",
  },
  {
    name: "Kuvalisbury",
    location: "125 Erdman Ridges",
    description: "Nam ut distinctio quam dolor.",
    rate: "47",
  },
  {
    name: "Taylor",
    location: "78382 Clovis Tunnel",
    description: "Molestiae provident quam voluptatem deserunt.",
    rate: "49",
  },
  {
    name: "Floville",
    location: "345 Mann Corner",
    description: "Laborum aliquid dolores delectus explicabo.",
    rate: "38",
  },
  {
    name: "Brendonport",
    location: "178 Casey Parks",
    description: "Perferendis aut distinctio nihil provident.",
    rate: "37",
  },
  {
    name: "Wymanfield",
    location: "210 Bayer Gateway",
    description: "Quam asperiores aut nesciunt facilis.",
    rate: "38",
  },
  {
    name: "East Moriahside",
    location: "8468 Abbott Green",
    description: "Quisquam ad vel animi vel.",
    rate: "40",
  },
  {
    name: "North Vinceborough",
    location: "2579 Littel Mill",
    description: "Minus quas vitae incidunt totam.",
    rate: "21",
  },
  {
    name: "West Maymie",
    location: "90193 Nikki Haven",
    description: "Dolore ut non incidunt eos.",
    rate: "43",
  },
  {
    name: "Hellerfurt",
    location: "47135 Maddison River",
    description: "Velit nihil et facere commodi.",
    rate: "41",
  },
  {
    name: "Dubuque",
    location: "5494 Earnest Parkway",
    description: "Necessitatibus possimus illum vel recusandae.",
    rate: "47",
  },
  {
    name: "Bethanyfield",
    location: "701 Oda Lake",
    description: "Tempore autem sint aut animi.",
    rate: "35",
  },
  {
    name: "Port Braxtonfield",
    location: "95038 Harold Grove",
    description: "Nulla sunt nam deserunt tenetur.",
    rate: "17",
  },
  {
    name: "Bakersfield",
    location: "994 Hirthe Vista",
    description: "Rem quae debitis quis quo.",
    rate: "31",
  },
  {
    name: "Breitenbergfort",
    location: "1700 Mortimer Park",
    description: "Consequatur commodi porro voluptas quibusdam.",
    rate: "12",
  },
  {
    name: "Lake Aniya",
    location: "23864 Darren Mountain",
    description: "Non velit quia et dolores.",
    rate: "29",
  },
  {
    name: "New Felipahaven",
    location: "2435 Labadie Flats",
    description: "Reprehenderit odit aut qui commodi.",
    rate: "36",
  },
  {
    name: "Dillanberg",
    location: "396 Murray Falls",
    description: "Ut non ut eum iure.",
    rate: "19",
  },
  {
    name: "Olemouth",
    location: "58542 Wolff Flats",
    description: "Nihil nihil suscipit id corrupti.",
    rate: "23",
  },
  {
    name: "Stammberg",
    location: "6931 Maribel Bridge",
    description: "Inventore voluptatem ex et nostrum.",
    rate: "42",
  },
  {
    name: "North Fredrick",
    location: "45276 Deonte Springs",
    description: "Modi quasi error nam cumque.",
    rate: "47",
  },
  {
    name: "Merced",
    location: "12804 Wisozk Club",
    description: "Est et at alias quidem.",
    rate: "12",
  },
  {
    name: "New Chasity",
    location: "662 Toney Locks",
    description: "Sed delectus ad corrupti ducimus.",
    rate: "27",
  },
  {
    name: "Farrellboro",
    location: "21812 Trantow Skyway",
    description: "Quibusdam dignissimos natus aut soluta.",
    rate: "17",
  },
  {
    name: "Prohaskahaven",
    location: "905 Reichel Valleys",
    description: "Animi qui inventore aut quasi.",
    rate: "37",
  },
  {
    name: "Pagacside",
    location: "422 Estell Bypass",
    description: "Voluptatibus rerum necessitatibus autem et.",
    rate: "34",
  },
  {
    name: "Leonorafurt",
    location: "27416 Syble Plains",
    description: "Non exercitationem aut voluptatibus ex.",
    rate: "25",
  },
  {
    name: "Dewittmouth",
    location: "65050 Daryl Locks",
    description: "Incidunt optio sint aut ratione.",
    rate: "50",
  },
  {
    name: "El Dorado Hills",
    location: "577 Raynor Mission",
    description: "Animi aut voluptas ut eum.",
    rate: "41",
  },
  {
    name: "Mattieborough",
    location: "699 Lauryn Bypass",
    description: "Dicta consequuntur maxime culpa explicabo.",
    rate: "41",
  },
  {
    name: "Watsonville",
    location: "78805 Alycia Pike",
    description: "Atque repudiandae officiis voluptates deleniti.",
    rate: "44",
  },
  {
    name: "Earlineshire",
    location: "3271 Magali Neck",
    description: "Aut harum modi id qui.",
    rate: "19",
  },
  {
    name: "Cormierport",
    location: "6190 Narciso Canyon",
    description: "Rerum quam ut quaerat nisi.",
    rate: "11",
  },
  {
    name: "Madisenfort",
    location: "999 Mayer Forges",
    description: "Totam nulla repudiandae deserunt temporibus.",
    rate: "50",
  },
  {
    name: "Grand Island",
    location: "5209 Piper Coves",
    description: "Libero laudantium corrupti optio voluptatum.",
    rate: "40",
  },
  {
    name: "Khalidside",
    location: "01029 Skylar Squares",
    description: "Placeat suscipit inventore odio deleniti.",
    rate: "33",
  },
  {
    name: "Fort Lilyancester",
    location: "1221 Lyla Village",
    description: "Qui molestiae at consectetur sed.",
    rate: "20",
  },
  {
    name: "West Lorna",
    location: "548 Beatty Port",
    description: "Sint est nostrum velit optio.",
    rate: "17",
  },
  {
    name: "Kulasberg",
    location: "1232 Louisa Forks",
    description: "Dolore eveniet natus consequatur magnam.",
    rate: "44",
  },
  {
    name: "Peytonborough",
    location: "6173 Marina Streets",
    description: "Consequuntur dolores dolor inventore animi.",
    rate: "13",
  },
  {
    name: "Zoeystad",
    location: "7525 Mable Forge",
    description: "Facere sint sit explicabo voluptate.",
    rate: "35",
  },
  {
    name: "Wymanburgh",
    location: "88797 Schmitt Summit",
    description: "Dolore optio sapiente nesciunt mollitia.",
    rate: "28",
  },
  {
    name: "New Kara",
    location: "987 Schuppe Keys",
    description: "Doloremque ratione molestiae soluta labore.",
    rate: "14",
  },
  {
    name: "Welchland",
    location: "605 Murazik Corners",
    description: "Molestias fugiat dolore quasi enim.",
    rate: "45",
  },
  {
    name: "Brentwood",
    location: "08206 Elliot Cove",
    description: "Dolore facere tempore ut quia.",
    rate: "25",
  },
];

export default siteData
