const siteData = [
  {
    name: "Arvidfield",
    location: "4387 Schmitt Cape",
    description: "Quisquam dolorem sint sit a.",
    price: "24",
    amenities: [
      "parking: true",
      "wheelchairAccessible: true",
      "petAllowed: false",
      "toilets: false",
      "campfire: false",
      "water: false",
      "showers: true",
      "trash: false",
      "hotTub: true",
      "picnicTable: false",
      "wifi: false",
      "cookingEquipment: true",
    ],
  },
  {
    name: "Ocala",
    location: "83045 Wisoky Extensions",
    description: "Assumenda facilis eos qui debitis.",
    price: "8",
    amenities: [
      "parking: true",
      "wheelchairAccessible: true",
      "petAllowed: false",
      "toilets: false",
      "campfire: false",
      "water: false",
      "showers: false",
      "trash: true",
      "hotTub: true",
      "picnicTable: true",
      "wifi: true",
      "cookingEquipment: true",
    ],
  },
  {
    name: "East Rebecca",
    location: "082 Rolfson Cliff",
    description: "Quia et aut eaque quis.",
    price: "40",
    amenities: [
      "parking: false",
      "wheelchairAccessible: true",
      "petAllowed: true",
      "toilets: false",
      "campfire: true",
      "water: false",
      "showers: false",
      "trash: false",
      "hotTub: false",
      "picnicTable: false",
      "wifi: true",
      "cookingEquipment: false",
    ],
  },
  {
    name: "West Janismouth",
    location: "51951 Jayden Burg",
    description: "Totam id ut placeat ipsam.",
    price: "19",
    amenities: [
      "parking: false",
      "wheelchairAccessible: true",
      "petAllowed: true",
      "toilets: false",
      "campfire: false",
      "water: false",
      "showers: true",
      "trash: true",
      "hotTub: false",
      "picnicTable: true",
      "wifi: true",
      "cookingEquipment: true",
    ],
  },
  {
    name: "North Camryn",
    location: "8881 Conn Estates",
    description: "Asperiores quia porro quidem excepturi.",
    price: "40",
    amenities: [
      "parking: false",
      "wheelchairAccessible: false",
      "petAllowed: true",
      "toilets: true",
      "campfire: true",
      "water: true",
      "showers: false",
      "trash: true",
      "hotTub: true",
      "picnicTable: true",
      "wifi: false",
      "cookingEquipment: true",
    ],
  },
  {
    name: "Fort Bud",
    location: "918 Dominic Ville",
    description: "Libero expedita ad quis dignissimos.",
    price: "9",
    amenities: [
      "parking: true",
      "wheelchairAccessible: true",
      "petAllowed: true",
      "toilets: true",
      "campfire: true",
      "water: true",
      "showers: true",
      "trash: false",
      "hotTub: true",
      "picnicTable: false",
      "wifi: false",
      "cookingEquipment: true",
    ],
  },
  {
    name: "Darrionland",
    location: "61873 Abernathy View",
    description: "Dolores saepe molestiae qui tenetur.",
    price: "36",
    amenities: [
      "parking: false",
      "wheelchairAccessible: false",
      "petAllowed: true",
      "toilets: false",
      "campfire: false",
      "water: false",
      "showers: true",
      "trash: true",
      "hotTub: true",
      "picnicTable: false",
      "wifi: true",
      "cookingEquipment: false",
    ],
  },
  {
    name: "Fort Kassandra",
    location: "01445 Wintheiser Forge",
    description: "Commodi quam officiis omnis adipisci.",
    price: "44",
    amenities: [
      "parking: false",
      "wheelchairAccessible: false",
      "petAllowed: true",
      "toilets: true",
      "campfire: true",
      "water: true",
      "showers: false",
      "trash: true",
      "hotTub: true",
      "picnicTable: true",
      "wifi: false",
      "cookingEquipment: true",
    ],
  },
  {
    name: "Aidaton",
    location: "94030 Holden Cove",
    description: "Sed accusamus consequatur et accusantium.",
    price: "33",
    amenities: [
      "parking: false",
      "wheelchairAccessible: true",
      "petAllowed: true",
      "toilets: true",
      "campfire: true",
      "water: true",
      "showers: false",
      "trash: true",
      "hotTub: true",
      "picnicTable: false",
      "wifi: true",
      "cookingEquipment: true",
    ],
  },
  {
    name: "Rippinville",
    location: "8168 Jovanny Hollow",
    description: "Rerum autem magni eos et.",
    price: "7",
    amenities: [
      "parking: false",
      "wheelchairAccessible: false",
      "petAllowed: false",
      "toilets: true",
      "campfire: false",
      "water: true",
      "showers: true",
      "trash: true",
      "hotTub: false",
      "picnicTable: false",
      "wifi: true",
      "cookingEquipment: true",
    ],
  },
  {
    name: "North Ulices",
    location: "6541 Barrows Pike",
    description: "Veritatis iusto sunt et accusantium.",
    price: "21",
    amenities: [
      "parking: false",
      "wheelchairAccessible: true",
      "petAllowed: true",
      "toilets: false",
      "campfire: true",
      "water: false",
      "showers: true",
      "trash: true",
      "hotTub: false",
      "picnicTable: true",
      "wifi: true",
      "cookingEquipment: false",
    ],
  },
  {
    name: "Zboncakburgh",
    location: "74338 Everett Circles",
    description: "Culpa molestiae sint voluptatem nam.",
    price: "39",
    amenities: [
      "parking: true",
      "wheelchairAccessible: true",
      "petAllowed: false",
      "toilets: true",
      "campfire: true",
      "water: true",
      "showers: false",
      "trash: true",
      "hotTub: true",
      "picnicTable: true",
      "wifi: true",
      "cookingEquipment: true",
    ],
  },
  {
    name: "Lake Linwoodshire",
    location: "293 Carter Springs",
    description: "Quia dolorum perferendis earum dolorem.",
    price: "33",
    amenities: [
      "parking: false",
      "wheelchairAccessible: true",
      "petAllowed: false",
      "toilets: false",
      "campfire: true",
      "water: true",
      "showers: false",
      "trash: true",
      "hotTub: false",
      "picnicTable: true",
      "wifi: false",
      "cookingEquipment: true",
    ],
  },
  {
    name: "Port Rubye",
    location: "273 Kassulke Lake",
    description: "Distinctio laudantium debitis aut veniam.",
    price: "46",
    amenities: [
      "parking: true",
      "wheelchairAccessible: true",
      "petAllowed: true",
      "toilets: false",
      "campfire: true",
      "water: true",
      "showers: true",
      "trash: true",
      "hotTub: true",
      "picnicTable: true",
      "wifi: false",
      "cookingEquipment: true",
    ],
  },
  {
    name: "South Geovanycester",
    location: "97494 Hilbert Haven",
    description: "Autem fuga nesciunt sed non.",
    price: "25",
    amenities: [
      "parking: false",
      "wheelchairAccessible: true",
      "petAllowed: true",
      "toilets: true",
      "campfire: true",
      "water: true",
      "showers: true",
      "trash: true",
      "hotTub: false",
      "picnicTable: true",
      "wifi: false",
      "cookingEquipment: false",
    ],
  },
  {
    name: "Port Larueport",
    location: "90822 Kelsi Inlet",
    description: "Deleniti nostrum voluptas dolorum qui.",
    price: "46",
    amenities: [
      "parking: true",
      "wheelchairAccessible: true",
      "petAllowed: true",
      "toilets: false",
      "campfire: true",
      "water: true",
      "showers: false",
      "trash: false",
      "hotTub: false",
      "picnicTable: true",
      "wifi: false",
      "cookingEquipment: false",
    ],
  },
  {
    name: "Harbertown",
    location: "146 Cruickshank Heights",
    description: "Ea autem qui eos deleniti.",
    price: "33",
    amenities: [
      "parking: false",
      "wheelchairAccessible: true",
      "petAllowed: false",
      "toilets: false",
      "campfire: true",
      "water: false",
      "showers: true",
      "trash: false",
      "hotTub: true",
      "picnicTable: true",
      "wifi: false",
      "cookingEquipment: false",
    ],
  },
  {
    name: "Lake Phoebe",
    location: "070 Emmanuel Via",
    description: "Consequatur et repudiandae iusto voluptatum.",
    price: "24",
    amenities: [
      "parking: true",
      "wheelchairAccessible: true",
      "petAllowed: true",
      "toilets: false",
      "campfire: true",
      "water: true",
      "showers: false",
      "trash: true",
      "hotTub: false",
      "picnicTable: false",
      "wifi: true",
      "cookingEquipment: false",
    ],
  },
  {
    name: "South Justenstead",
    location: "879 Huels Keys",
    description: "Et tenetur autem ipsam debitis.",
    price: "29",
    amenities: [
      "parking: true",
      "wheelchairAccessible: true",
      "petAllowed: true",
      "toilets: true",
      "campfire: true",
      "water: false",
      "showers: true",
      "trash: true",
      "hotTub: false",
      "picnicTable: true",
      "wifi: false",
      "cookingEquipment: true",
    ],
  },
  {
    name: "North Celinecester",
    location: "3610 Lee Squares",
    description: "Ut molestiae quam quaerat quas.",
    price: "2",
    amenities: [
      "parking: true",
      "wheelchairAccessible: true",
      "petAllowed: false",
      "toilets: true",
      "campfire: false",
      "water: true",
      "showers: false",
      "trash: true",
      "hotTub: true",
      "picnicTable: false",
      "wifi: false",
      "cookingEquipment: false",
    ],
  },
  {
    name: "Ronnyside",
    location: "77645 Becker Knolls",
    description: "Sit et dignissimos beatae blanditiis.",
    price: "26",
    amenities: [
      "parking: false",
      "wheelchairAccessible: false",
      "petAllowed: false",
      "toilets: false",
      "campfire: false",
      "water: false",
      "showers: true",
      "trash: false",
      "hotTub: true",
      "picnicTable: false",
      "wifi: true",
      "cookingEquipment: true",
    ],
  },
  {
    name: "New Blanchecester",
    location: "3494 Kuvalis Causeway",
    description: "Architecto facilis cumque impedit error.",
    price: "40",
    amenities: [
      "parking: false",
      "wheelchairAccessible: true",
      "petAllowed: true",
      "toilets: true",
      "campfire: false",
      "water: true",
      "showers: false",
      "trash: true",
      "hotTub: true",
      "picnicTable: false",
      "wifi: false",
      "cookingEquipment: true",
    ],
  },
  {
    name: "New Judeburgh",
    location: "92272 Abernathy Estates",
    description: "Et corporis neque deleniti dignissimos.",
    price: "46",
    amenities: [
      "parking: true",
      "wheelchairAccessible: true",
      "petAllowed: false",
      "toilets: true",
      "campfire: true",
      "water: false",
      "showers: true",
      "trash: false",
      "hotTub: true",
      "picnicTable: true",
      "wifi: true",
      "cookingEquipment: true",
    ],
  },
  {
    name: "West Raquel",
    location: "206 Terrence Causeway",
    description: "Nihil voluptatem eveniet harum voluptatibus.",
    price: "7",
    amenities: [
      "parking: true",
      "wheelchairAccessible: true",
      "petAllowed: false",
      "toilets: false",
      "campfire: true",
      "water: false",
      "showers: false",
      "trash: false",
      "hotTub: false",
      "picnicTable: true",
      "wifi: false",
      "cookingEquipment: false",
    ],
  },
  {
    name: "Predovicland",
    location: "0782 Little Manor",
    description: "Et corrupti ullam blanditiis nostrum.",
    price: "6",
    amenities: [
      "parking: true",
      "wheelchairAccessible: true",
      "petAllowed: true",
      "toilets: true",
      "campfire: true",
      "water: false",
      "showers: true",
      "trash: true",
      "hotTub: true",
      "picnicTable: true",
      "wifi: false",
      "cookingEquipment: false",
    ],
  },
  {
    name: "Marlonland",
    location: "0458 Sanford Ranch",
    description: "Et incidunt tenetur eum accusantium.",
    price: "46",
    amenities: [
      "parking: true",
      "wheelchairAccessible: true",
      "petAllowed: false",
      "toilets: true",
      "campfire: false",
      "water: true",
      "showers: true",
      "trash: false",
      "hotTub: false",
      "picnicTable: true",
      "wifi: true",
      "cookingEquipment: true",
    ],
  },
  {
    name: "Cleveland",
    location: "9167 Wolff Island",
    description: "Provident accusantium expedita deserunt odit.",
    price: "7",
    amenities: [
      "parking: false",
      "wheelchairAccessible: true",
      "petAllowed: false",
      "toilets: false",
      "campfire: true",
      "water: false",
      "showers: false",
      "trash: true",
      "hotTub: false",
      "picnicTable: false",
      "wifi: false",
      "cookingEquipment: true",
    ],
  },
  {
    name: "Lake Fannie",
    location: "81171 Hudson Mountains",
    description: "Deleniti architecto iusto nisi aut.",
    price: "50",
    amenities: [
      "parking: true",
      "wheelchairAccessible: false",
      "petAllowed: true",
      "toilets: true",
      "campfire: true",
      "water: true",
      "showers: true",
      "trash: false",
      "hotTub: true",
      "picnicTable: false",
      "wifi: true",
      "cookingEquipment: true",
    ],
  },
  {
    name: "Albany",
    location: "1683 Leannon Corner",
    description: "Mollitia nostrum architecto rerum placeat.",
    price: "7",
    amenities: [
      "parking: true",
      "wheelchairAccessible: true",
      "petAllowed: false",
      "toilets: true",
      "campfire: true",
      "water: true",
      "showers: false",
      "trash: true",
      "hotTub: false",
      "picnicTable: false",
      "wifi: false",
      "cookingEquipment: false",
    ],
  },
  {
    name: "Leilaboro",
    location: "146 Ryan Ferry",
    description: "Mollitia ut laborum omnis pariatur.",
    price: "9",
    amenities: [
      "parking: false",
      "wheelchairAccessible: true",
      "petAllowed: true",
      "toilets: true",
      "campfire: false",
      "water: true",
      "showers: true",
      "trash: true",
      "hotTub: true",
      "picnicTable: true",
      "wifi: false",
      "cookingEquipment: true",
    ],
  },
  {
    name: "Vacaville",
    location: "9314 Geraldine Square",
    description: "Voluptatem aliquam sunt provident deleniti.",
    price: "6",
    amenities: [
      "parking: true",
      "wheelchairAccessible: false",
      "petAllowed: true",
      "toilets: false",
      "campfire: false",
      "water: false",
      "showers: true",
      "trash: true",
      "hotTub: false",
      "picnicTable: true",
      "wifi: true",
      "cookingEquipment: false",
    ],
  },
  {
    name: "Sawaynboro",
    location: "19610 Natalie Locks",
    description: "Sint dicta non aperiam omnis.",
    price: "9",
    amenities: [
      "parking: true",
      "wheelchairAccessible: true",
      "petAllowed: true",
      "toilets: false",
      "campfire: true",
      "water: true",
      "showers: true",
      "trash: true",
      "hotTub: true",
      "picnicTable: false",
      "wifi: true",
      "cookingEquipment: true",
    ],
  },
  {
    name: "Fort Herminio",
    location: "46674 Hoeger Circle",
    description: "Non eos quia quia perspiciatis.",
    price: "13",
    amenities: [
      "parking: true",
      "wheelchairAccessible: true",
      "petAllowed: true",
      "toilets: false",
      "campfire: false",
      "water: true",
      "showers: true",
      "trash: true",
      "hotTub: true",
      "picnicTable: true",
      "wifi: true",
      "cookingEquipment: true",
    ],
  },
  {
    name: "Lake Dixiehaven",
    location: "2767 Raynor Drive",
    description: "Deleniti ut dolore earum numquam.",
    price: "32",
    amenities: [
      "parking: false",
      "wheelchairAccessible: true",
      "petAllowed: true",
      "toilets: true",
      "campfire: false",
      "water: true",
      "showers: false",
      "trash: true",
      "hotTub: false",
      "picnicTable: true",
      "wifi: true",
      "cookingEquipment: true",
    ],
  },
  {
    name: "Pine Hills",
    location: "7924 Bailey Pass",
    description: "Harum sed accusamus a corrupti.",
    price: "34",
    amenities: [
      "parking: true",
      "wheelchairAccessible: true",
      "petAllowed: true",
      "toilets: true",
      "campfire: false",
      "water: false",
      "showers: true",
      "trash: false",
      "hotTub: true",
      "picnicTable: true",
      "wifi: false",
      "cookingEquipment: false",
    ],
  },
  {
    name: "New Alainamouth",
    location: "0797 Yvette Parks",
    description: "Magnam laudantium et ut ut.",
    price: "32",
    amenities: [
      "parking: true",
      "wheelchairAccessible: false",
      "petAllowed: true",
      "toilets: true",
      "campfire: false",
      "water: true",
      "showers: false",
      "trash: true",
      "hotTub: false",
      "picnicTable: false",
      "wifi: true",
      "cookingEquipment: true",
    ],
  },
  {
    name: "Gastonia",
    location: "26236 Pfeffer Street",
    description: "Possimus nobis commodi amet quo.",
    price: "45",
    amenities: [
      "parking: true",
      "wheelchairAccessible: true",
      "petAllowed: true",
      "toilets: true",
      "campfire: false",
      "water: false",
      "showers: true",
      "trash: true",
      "hotTub: false",
      "picnicTable: true",
      "wifi: true",
      "cookingEquipment: true",
    ],
  },
  {
    name: "Lehi",
    location: "031 Arnulfo Tunnel",
    description: "Facere delectus consectetur omnis debitis.",
    price: "19",
    amenities: [
      "parking: true",
      "wheelchairAccessible: false",
      "petAllowed: false",
      "toilets: true",
      "campfire: false",
      "water: true",
      "showers: false",
      "trash: false",
      "hotTub: true",
      "picnicTable: false",
      "wifi: true",
      "cookingEquipment: false",
    ],
  },
  {
    name: "Schaeferport",
    location: "80959 Hodkiewicz Harbors",
    description: "Ut possimus maiores quisquam reprehenderit.",
    price: "31",
    amenities: [
      "parking: false",
      "wheelchairAccessible: true",
      "petAllowed: true",
      "toilets: true",
      "campfire: true",
      "water: false",
      "showers: false",
      "trash: true",
      "hotTub: true",
      "picnicTable: false",
      "wifi: false",
      "cookingEquipment: false",
    ],
  },
  {
    name: "West Gersonstead",
    location: "588 Josiane Shore",
    description: "Occaecati inventore nulla hic earum.",
    price: "44",
    amenities: [
      "parking: true",
      "wheelchairAccessible: true",
      "petAllowed: true",
      "toilets: true",
      "campfire: true",
      "water: true",
      "showers: false",
      "trash: true",
      "hotTub: true",
      "picnicTable: true",
      "wifi: true",
      "cookingEquipment: true",
    ],
  },
  {
    name: "Nienowhaven",
    location: "512 Blick Turnpike",
    description: "Et ex cumque exercitationem quo.",
    price: "18",
    amenities: [
      "parking: true",
      "wheelchairAccessible: true",
      "petAllowed: true",
      "toilets: false",
      "campfire: false",
      "water: false",
      "showers: true",
      "trash: false",
      "hotTub: true",
      "picnicTable: false",
      "wifi: true",
      "cookingEquipment: false",
    ],
  },
  {
    name: "Kennewick",
    location: "506 Hettinger Curve",
    description: "Ea itaque iusto deleniti sit.",
    price: "6",
    amenities: [
      "parking: true",
      "wheelchairAccessible: true",
      "petAllowed: false",
      "toilets: false",
      "campfire: true",
      "water: true",
      "showers: true",
      "trash: false",
      "hotTub: true",
      "picnicTable: true",
      "wifi: false",
      "cookingEquipment: true",
    ],
  },
  {
    name: "Lake Ilashire",
    location: "677 Nitzsche Course",
    description: "Qui odio ab incidunt qui.",
    price: "17",
    amenities: [
      "parking: false",
      "wheelchairAccessible: true",
      "petAllowed: false",
      "toilets: true",
      "campfire: false",
      "water: true",
      "showers: false",
      "trash: true",
      "hotTub: false",
      "picnicTable: true",
      "wifi: false",
      "cookingEquipment: false",
    ],
  },
  {
    name: "Aiyanaland",
    location: "91501 Hadley Glens",
    description: "Voluptatem possimus soluta reiciendis maiores.",
    price: "9",
    amenities: [
      "parking: true",
      "wheelchairAccessible: true",
      "petAllowed: true",
      "toilets: true",
      "campfire: false",
      "water: true",
      "showers: false",
      "trash: true",
      "hotTub: true",
      "picnicTable: true",
      "wifi: true",
      "cookingEquipment: true",
    ],
  },
  {
    name: "Portage",
    location: "4481 Cathrine Plains",
    description: "Rerum officia et non fugiat.",
    price: "28",
    amenities: [
      "parking: true",
      "wheelchairAccessible: true",
      "petAllowed: false",
      "toilets: true",
      "campfire: true",
      "water: false",
      "showers: false",
      "trash: false",
      "hotTub: true",
      "picnicTable: true",
      "wifi: false",
      "cookingEquipment: false",
    ],
  },
  {
    name: "West Jordanecester",
    location: "073 Jada Drive",
    description: "Et minus in qui quibusdam.",
    price: "25",
    amenities: [
      "parking: false",
      "wheelchairAccessible: true",
      "petAllowed: true",
      "toilets: true",
      "campfire: true",
      "water: true",
      "showers: false",
      "trash: true",
      "hotTub: true",
      "picnicTable: true",
      "wifi: false",
      "cookingEquipment: true",
    ],
  },
  {
    name: "Tryciatown",
    location: "9419 Maxine Mount",
    description: "Consequatur quis qui ex vitae.",
    price: "3",
    amenities: [
      "parking: true",
      "wheelchairAccessible: false",
      "petAllowed: true",
      "toilets: true",
      "campfire: true",
      "water: true",
      "showers: true",
      "trash: true",
      "hotTub: false",
      "picnicTable: false",
      "wifi: false",
      "cookingEquipment: false",
    ],
  },
  {
    name: "West Berniemouth",
    location: "1024 McLaughlin Shoal",
    description: "Esse quos laborum natus laudantium.",
    price: "41",
    amenities: [
      "parking: true",
      "wheelchairAccessible: true",
      "petAllowed: false",
      "toilets: true",
      "campfire: true",
      "water: true",
      "showers: true",
      "trash: false",
      "hotTub: false",
      "picnicTable: false",
      "wifi: true",
      "cookingEquipment: false",
    ],
  },
  {
    name: "Yadiraborough",
    location: "4576 Laverna Courts",
    description: "Dolor quam corrupti qui a.",
    price: "18",
    amenities: [
      "parking: false",
      "wheelchairAccessible: false",
      "petAllowed: true",
      "toilets: true",
      "campfire: false",
      "water: true",
      "showers: true",
      "trash: false",
      "hotTub: false",
      "picnicTable: false",
      "wifi: true",
      "cookingEquipment: true",
    ],
  },
  {
    name: "Ferrytown",
    location: "833 Sawayn Motorway",
    description: "Nemo eum optio nesciunt natus.",
    price: "26",
    amenities: [
      "parking: true",
      "wheelchairAccessible: false",
      "petAllowed: false",
      "toilets: true",
      "campfire: false",
      "water: true",
      "showers: false",
      "trash: true",
      "hotTub: false",
      "picnicTable: true",
      "wifi: true",
      "cookingEquipment: false",
    ],
  },
];

export default siteData;
